
version: '3.8'

services:
  webapp:
    build: .
    ports:
      - "8080:8080"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8080/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 15s
    environment:
      - NODE_ENV=production
      - SERVER_URL=http://168.231.76.164:8080
      - SUPABASE_URL=https://avnyubdiccodzznnbmzx.supabase.co
      - SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF2bnl1YmRpY2NvZHp6bm5ibXp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxNDE3NDMsImV4cCI6MjA2MjcxNzc0M30.y556Ux2sKfssoUZ3V-xQFzNtVfDiBf_n-YOtnFYKk7o
      # Add your custom environment variables below as needed
      # - CUSTOM_VARIABLE=custom_value
