// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://avnyubdiccodzznnbmzx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF2bnl1YmRpY2NvZHp6bm5ibXp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxNDE3NDMsImV4cCI6MjA2MjcxNzc0M30.y556Ux2sKfssoUZ3V-xQFzNtVfDiBf_n-YOtnFYKk7o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);